---
- name: Install krb5-workstation
  ansible.builtin.dnf:
    name: krb5-workstation
    update_cache: true
    state: present

- name: Configure krb5-workstation
  ansible.builtin.template:
    src: krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: '0644'
